### PR TITLE
Merge milestone-6 to development

### PR DESCRIPTION
**Pull request by Blasco9**
In this branch, I implemented the friendship model with two rows for each relationship, refactored previous methods of the user model and refactored user views and tests to work with the new friendship model

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
## Hi @Blasco9! Very nice project! :wave: 

### A few changes before it can be approved :eyes:  

Please, write the integrations tests and with almost everything concerning the friendships requirements.

screen

Kindly make the changes and submit a new code review request.
Thanks

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Comment by Blasco9** [comment]
Hello @Anna-Myzukina, I wrote the unit tests and integration tests in the previous milestone. If I'm missing any specific scenario to test, could you please point it out? Thanks!

**Review by uche-inyama — APPROVED** [review]
## Approved.

Hi team :wave: 

This milestone is approved.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Comment by Blasco9** [comment]
Thanks for your review @uche-inyama!

**Pull request merged**
